-- ============================================================================
-- Migration: 002_seed_data
-- Description: Comprehensive seed data for development and testing
-- Date: 2025-01-06
-- ============================================================================

-- NOTE: Passwords are hashed using bcrypt (the actual hash will be generated by the backend)
-- For testing, we'll insert placeholder hashes that the backend can replace

-- ============================================================================
-- LEAGUES
-- ============================================================================

INSERT INTO leagues (id, external_id, name, country, logo_url, season, is_active, display_order) VALUES
(1, 39, 'Premier League', 'England', 'https://media.api-sports.io/football/leagues/39.png', '2024/2025', 1, 1),
(2, 140, 'La Liga', 'Spain', 'https://media.api-sports.io/football/leagues/140.png', '2024/2025', 1, 2),
(3, 78, 'Bundesliga', 'Germany', 'https://media.api-sports.io/football/leagues/78.png', '2024/2025', 1, 3),
(4, 135, 'Serie A', 'Italy', 'https://media.api-sports.io/football/leagues/135.png', '2024/2025', 1, 4),
(5, 61, 'Ligue 1', 'France', 'https://media.api-sports.io/football/leagues/61.png', '2024/2025', 1, 5),
(6, 2, 'UEFA Champions League', 'Europe', 'https://media.api-sports.io/football/leagues/2.png', '2024/2025', 1, 6),
(7, 3, 'UEFA Europa League', 'Europe', 'https://media.api-sports.io/football/leagues/3.png', '2024/2025', 1, 7);

-- ============================================================================
-- VENUES
-- ============================================================================

INSERT INTO venues (id, external_id, name, city, country, capacity, surface, image_url) VALUES
(1, 556, 'Emirates Stadium', 'London', 'England', 60260, 'grass', 'https://media.api-sports.io/football/venues/556.png'),
(2, 508, 'Stamford Bridge', 'London', 'England', 40341, 'grass', 'https://media.api-sports.io/football/venues/508.png'),
(3, 550, 'Old Trafford', 'Manchester', 'England', 76212, 'grass', 'https://media.api-sports.io/football/venues/550.png'),
(4, 555, 'Anfield', 'Liverpool', 'England', 53394, 'grass', 'https://media.api-sports.io/football/venues/555.png'),
(5, 1456, 'Camp Nou', 'Barcelona', 'Spain', 99354, 'grass', 'https://media.api-sports.io/football/venues/1456.png'),
(6, 1459, 'Santiago Bernabéu', 'Madrid', 'Spain', 81044, 'grass', 'https://media.api-sports.io/football/venues/1459.png'),
(7, 738, 'Allianz Arena', 'München', 'Germany', 75000, 'grass', 'https://media.api-sports.io/football/venues/738.png'),
(8, 740, 'Signal Iduna Park', 'Dortmund', 'Germany', 81365, 'grass', 'https://media.api-sports.io/football/venues/740.png');

-- ============================================================================
-- TEAMS
-- ============================================================================

INSERT INTO teams (id, external_id, name, short_name, logo_url, country, founded, venue_id) VALUES
-- Premier League
(1, 42, 'Arsenal', 'Arsenal', 'https://media.api-sports.io/football/teams/42.png', 'England', 1886, 1),
(2, 49, 'Chelsea', 'Chelsea', 'https://media.api-sports.io/football/teams/49.png', 'England', 1905, 2),
(3, 33, 'Manchester United', 'Man United', 'https://media.api-sports.io/football/teams/33.png', 'England', 1878, 3),
(4, 40, 'Liverpool', 'Liverpool', 'https://media.api-sports.io/football/teams/40.png', 'England', 1892, 4),
(5, 50, 'Manchester City', 'Man City', 'https://media.api-sports.io/football/teams/50.png', 'England', 1880, NULL),
(6, 47, 'Tottenham', 'Spurs', 'https://media.api-sports.io/football/teams/47.png', 'England', 1882, NULL),
-- La Liga
(7, 529, 'Barcelona', 'Barcelona', 'https://media.api-sports.io/football/teams/529.png', 'Spain', 1899, 5),
(8, 541, 'Real Madrid', 'Real Madrid', 'https://media.api-sports.io/football/teams/541.png', 'Spain', 1902, 6),
(9, 530, 'Atlético Madrid', 'Atlético', 'https://media.api-sports.io/football/teams/530.png', 'Spain', 1903, NULL),
(10, 532, 'Valencia', 'Valencia', 'https://media.api-sports.io/football/teams/532.png', 'Spain', 1919, NULL),
-- Bundesliga
(11, 157, 'Bayern München', 'Bayern', 'https://media.api-sports.io/football/teams/157.png', 'Germany', 1900, 7),
(12, 165, 'Borussia Dortmund', 'Dortmund', 'https://media.api-sports.io/football/teams/165.png', 'Germany', 1909, 8),
(13, 173, 'RB Leipzig', 'RB Leipzig', 'https://media.api-sports.io/football/teams/173.png', 'Germany', 2009, NULL),
(14, 168, 'Bayer Leverkusen', 'Leverkusen', 'https://media.api-sports.io/football/teams/168.png', 'Germany', 1904, NULL),
-- Serie A
(15, 489, 'Juventus', 'Juventus', 'https://media.api-sports.io/football/teams/489.png', 'Italy', 1897, NULL),
(16, 487, 'AC Milan', 'Milan', 'https://media.api-sports.io/football/teams/487.png', 'Italy', 1899, NULL),
(17, 505, 'Inter', 'Inter', 'https://media.api-sports.io/football/teams/505.png', 'Italy', 1908, NULL),
(18, 492, 'Napoli', 'Napoli', 'https://media.api-sports.io/football/teams/492.png', 'Italy', 1926, NULL),
-- Ligue 1
(19, 85, 'Paris Saint Germain', 'PSG', 'https://media.api-sports.io/football/teams/85.png', 'France', 1970, NULL),
(20, 81, 'Marseille', 'Marseille', 'https://media.api-sports.io/football/teams/81.png', 'France', 1899, NULL);

-- ============================================================================
-- PREDICTION TYPES
-- ============================================================================

INSERT INTO prediction_types (id, name, category, description, is_active) VALUES
(1, 'Home Win', 'result', 'Home team to win the match', 1),
(2, 'Draw', 'result', 'Match ends in a draw', 1),
(3, 'Away Win', 'result', 'Away team to win the match', 1),
(4, 'Over 0.5 Goals', 'goals', 'Total goals over 0.5', 1),
(5, 'Over 1.5 Goals', 'goals', 'Total goals over 1.5', 1),
(6, 'Over 2.5 Goals', 'goals', 'Total goals over 2.5', 1),
(7, 'Over 3.5 Goals', 'goals', 'Total goals over 3.5', 1),
(8, 'Under 2.5 Goals', 'goals', 'Total goals under 2.5', 1),
(9, 'Under 3.5 Goals', 'goals', 'Total goals under 3.5', 1),
(10, 'Both Teams to Score - Yes', 'both_teams', 'Both teams score at least one goal', 1),
(11, 'Both Teams to Score - No', 'both_teams', 'At least one team fails to score', 1),
(12, 'Home Win or Draw', 'result', 'Home team wins or draw (Double Chance)', 1),
(13, 'Away Win or Draw', 'result', 'Away team wins or draw (Double Chance)', 1),
(14, 'Over 8.5 Corners', 'corners', 'Total corners over 8.5', 1),
(15, 'Over 10.5 Corners', 'corners', 'Total corners over 10.5', 1);

-- ============================================================================
-- AI MODELS
-- ============================================================================

INSERT INTO ai_models (id, name, version, model_type, provider, description, weight, is_active) VALUES
(1, 'GPT-4 Turbo', '4.0', 'llm', 'OpenAI', 'Advanced language model for match analysis', 0.50, 1),
(2, 'Claude 3.5 Sonnet', '3.5', 'llm', 'Anthropic', 'Reasoning-focused model for predictions', 0.50, 1),
(3, 'Llama 3.8B', '3.8B', 'llm', 'Meta/Cloudflare', 'Lightweight model for quick predictions', 0.50, 1),
(4, 'Poisson Distribution', '1.0', 'statistical', 'Custom', 'Goal-based probability model', 0.30, 1),
(5, 'Elo Rating System', '1.0', 'statistical', 'Custom', 'Team strength rating system', 0.20, 1),
(6, 'Ensemble Model', '2.0', 'ensemble', 'Custom', 'Weighted combination of all models', 1.00, 1);

-- ============================================================================
-- BOOKMAKERS
-- ============================================================================

INSERT INTO bookmakers (id, name, display_name, logo_url, website_url, is_active, country_restrictions) VALUES
(1, 'bet365', 'Bet365', 'https://via.placeholder.com/150x50/1E3A5F/FFFFFF?text=Bet365', 'https://www.bet365.com', 1, NULL),
(2, 'william_hill', 'William Hill', 'https://via.placeholder.com/150x50/004833/FFFFFF?text=William+Hill', 'https://www.williamhill.com', 1, NULL),
(3, 'betway', 'Betway', 'https://via.placeholder.com/150x50/000000/FFFFFF?text=Betway', 'https://www.betway.com', 1, NULL),
(4, 'unibet', 'Unibet', 'https://via.placeholder.com/150x50/1D9B4E/FFFFFF?text=Unibet', 'https://www.unibet.com', 1, NULL),
(5, 'paddy_power', 'Paddy Power', 'https://via.placeholder.com/150x50/00A859/FFFFFF?text=Paddy+Power', 'https://www.paddypower.com', 1, NULL),
(6, 'skybet', 'Sky Bet', 'https://via.placeholder.com/150x50/001E62/FFFFFF?text=Sky+Bet', 'https://www.skybet.com', 1, NULL),
(7, 'betfair', 'Betfair', 'https://via.placeholder.com/150x50/FFBA08/000000?text=Betfair', 'https://www.betfair.com', 1, NULL),
(8, 'coral', 'Coral', 'https://via.placeholder.com/150x50/DA291C/FFFFFF?text=Coral', 'https://www.coral.co.uk', 1, NULL);

-- ============================================================================
-- ACHIEVEMENT DEFINITIONS
-- ============================================================================

INSERT INTO achievement_definitions (id, name, category, description, badge_icon, xp_reward, coin_reward, requirement_type, requirement_value, is_active) VALUES
-- Prediction Accuracy Achievements
(1, 'First Blood', 'prediction_accuracy', 'Make your first correct prediction', '🎯', 100, 50, 'correct_predictions', 1, 1),
(2, 'Sharpshooter', 'prediction_accuracy', 'Get 10 predictions correct', '🎯', 250, 100, 'correct_predictions', 10, 1),
(3, 'Prophet', 'prediction_accuracy', 'Achieve 75% accuracy with 20+ predictions', '🔮', 500, 250, 'accuracy_threshold', 75, 1),
(4, 'Oracle', 'prediction_accuracy', 'Achieve 80% accuracy with 50+ predictions', '👁️', 1000, 500, 'accuracy_threshold', 80, 1),
(5, 'Fortune Teller', 'prediction_accuracy', 'Achieve 85% accuracy with 100+ predictions', '🌟', 2000, 1000, 'accuracy_threshold', 85, 1),

-- Streak Achievements
(6, 'Hot Streak', 'streak', 'Get 3 predictions correct in a row', '🔥', 150, 75, 'streak', 3, 1),
(7, 'On Fire', 'streak', 'Get 5 predictions correct in a row', '🔥🔥', 300, 150, 'streak', 5, 1),
(8, 'Unstoppable', 'streak', 'Get 10 predictions correct in a row', '🔥🔥🔥', 750, 400, 'streak', 10, 1),
(9, 'Legendary Streak', 'streak', 'Get 15 predictions correct in a row', '👑', 1500, 800, 'streak', 15, 1),

-- Volume Achievements
(10, 'Getting Started', 'volume', 'Make 5 predictions', '📊', 50, 25, 'total_predictions', 5, 1),
(11, 'Active Predictor', 'volume', 'Make 25 predictions', '📊', 200, 100, 'total_predictions', 25, 1),
(12, 'Prediction Machine', 'volume', 'Make 100 predictions', '⚙️', 500, 250, 'total_predictions', 100, 1),
(13, 'Elite Analyst', 'volume', 'Make 500 predictions', '💎', 1500, 750, 'total_predictions', 500, 1),

-- Profit Achievements
(14, 'First Profit', 'profit', 'Achieve +10 units profit', '💰', 200, 100, 'profit_units', 10, 1),
(15, 'Money Maker', 'profit', 'Achieve +50 units profit', '💰💰', 500, 250, 'profit_units', 50, 1),
(16, 'High Roller', 'profit', 'Achieve +100 units profit', '💰💰💰', 1000, 500, 'profit_units', 100, 1),
(17, 'Millionaire Mindset', 'profit', 'Achieve +500 units profit', '🏆', 5000, 2500, 'profit_units', 500, 1),

-- Social Achievements
(18, 'Social Butterfly', 'social', 'Get 10 followers', '🦋', 150, 75, 'followers', 10, 1),
(19, 'Influencer', 'social', 'Get 50 followers', '⭐', 500, 250, 'followers', 50, 1),
(20, 'Celebrity Tipster', 'social', 'Get 100 followers', '🌟', 1000, 500, 'followers', 100, 1),

-- Special Achievements
(21, 'Early Adopter', 'special', 'Join in the first month', '🚀', 500, 250, 'manual', 0, 1),
(22, 'Value Hunter', 'special', 'Find 10 value bets with EV > 10%', '💎', 750, 400, 'value_bets_found', 10, 1),
(23, 'Arbitrage Master', 'special', 'Find 5 arbitrage opportunities', '🎰', 1000, 500, 'arbitrage_found', 5, 1),
(24, 'Perfect Weekend', 'special', 'Get all weekend predictions correct (min 5)', '🎉', 1000, 500, 'perfect_weekend', 1, 1);

-- ============================================================================
-- CHALLENGE DEFINITIONS
-- ============================================================================

INSERT INTO challenge_definitions (id, name, description, challenge_type, requirement_type, requirement_value, xp_reward, coin_reward, start_date, end_date, is_active) VALUES
-- Daily Challenges
(1, 'Daily Predictor', 'Make 3 predictions today', 'daily', 'predictions_today', 3, 50, 25, date('now'), date('now', '+1 day'), 1),
(2, 'Accuracy Focus', 'Achieve 70% accuracy today (min 3 predictions)', 'daily', 'accuracy_today', 70, 100, 50, date('now'), date('now', '+1 day'), 1),
(3, 'Value Seeker', 'Find 1 value bet today', 'daily', 'value_bets_today', 1, 75, 40, date('now'), date('now', '+1 day'), 1),

-- Weekly Challenges
(4, 'Weekly Warrior', 'Make 15 predictions this week', 'weekly', 'predictions_week', 15, 300, 150, date('now', 'weekday 1', '-7 days'), date('now', 'weekday 1'), 1),
(5, 'Profit Week', 'Achieve +5 units profit this week', 'weekly', 'profit_week', 5, 500, 250, date('now', 'weekday 1', '-7 days'), date('now', 'weekday 1'), 1),
(6, 'Social Sharer', 'Share 5 predictions this week', 'weekly', 'shares_week', 5, 200, 100, date('now', 'weekday 1', '-7 days'), date('now', 'weekday 1'), 1);

-- ============================================================================
-- TOURNAMENTS
-- ============================================================================

INSERT INTO tournaments (id, name, description, tournament_type, entry_fee_coins, prize_pool_coins, max_participants, start_date, end_date, status) VALUES
(1, 'Premier League Predictions - Week 1', 'Predict all Premier League matches this weekend', 'weekly', 100, 5000, 1000, date('now'), date('now', '+7 days'), 'active'),
(2, 'Champions League Challenge', 'Predict Champions League matchday results', 'weekly', 200, 10000, 500, date('now'), date('now', '+7 days'), 'active'),
(3, 'January Monthly Championship', 'Month-long prediction competition', 'monthly', 500, 50000, 10000, '2025-01-01', '2025-01-31', 'active');

-- ============================================================================
-- SAMPLE MATCHES (for today/upcoming)
-- ============================================================================

INSERT INTO matches (id, external_id, league_id, home_team_id, away_team_id, venue_id, kick_off_time, status) VALUES
(1, 1001, 1, 1, 2, 1, datetime('now', '+2 hours'), 'upcoming'),
(2, 1002, 1, 3, 4, 3, datetime('now', '+4 hours'), 'upcoming'),
(3, 1003, 1, 5, 6, NULL, datetime('now', '+6 hours'), 'upcoming'),
(4, 1004, 2, 7, 8, 5, datetime('now', '+3 hours'), 'upcoming'),
(5, 1005, 2, 9, 10, NULL, datetime('now', '+5 hours'), 'upcoming'),
(6, 1006, 3, 11, 12, 7, datetime('now', '+1 hour'), 'upcoming'),
(7, 1007, 3, 13, 14, NULL, datetime('now', '+7 hours'), 'upcoming'),
(8, 1008, 4, 15, 16, NULL, datetime('now', '+2.5 hours'), 'upcoming'),
(9, 1009, 4, 17, 18, NULL, datetime('now', '+4.5 hours'), 'upcoming'),
(10, 1010, 5, 19, 20, NULL, datetime('now', '+3.5 hours'), 'upcoming');

-- ============================================================================
-- SAMPLE ODDS (for the matches above)
-- ============================================================================

-- Match 1: Arsenal vs Chelsea
INSERT INTO odds (match_id, bookmaker_id, prediction_type, market_name, odds_value) VALUES
(1, 1, 'Home Win', '1X2', 1.75),
(1, 1, 'Draw', '1X2', 3.60),
(1, 1, 'Away Win', '1X2', 4.50),
(1, 1, 'Over 2.5 Goals', 'Goals O/U', 1.90),
(1, 1, 'Both Teams to Score - Yes', 'BTTS', 1.70),
(1, 2, 'Home Win', '1X2', 1.80),
(1, 2, 'Draw', '1X2', 3.50),
(1, 2, 'Away Win', '1X2', 4.40),
(1, 3, 'Home Win', '1X2', 1.78),
(1, 3, 'Over 2.5 Goals', 'Goals O/U', 1.85);

-- Match 4: Barcelona vs Real Madrid
INSERT INTO odds (match_id, bookmaker_id, prediction_type, market_name, odds_value) VALUES
(4, 1, 'Home Win', '1X2', 2.10),
(4, 1, 'Draw', '1X2', 3.40),
(4, 1, 'Away Win', '1X2', 3.20),
(4, 1, 'Over 2.5 Goals', 'Goals O/U', 1.75),
(4, 1, 'Both Teams to Score - Yes', 'BTTS', 1.55),
(4, 2, 'Home Win', '1X2', 2.15),
(4, 2, 'Draw', '1X2', 3.30),
(4, 2, 'Away Win', '1X2', 3.10);

-- Match 6: Bayern vs Dortmund
INSERT INTO odds (match_id, bookmaker_id, prediction_type, market_name, odds_value) VALUES
(6, 1, 'Home Win', '1X2', 1.65),
(6, 1, 'Draw', '1X2', 3.80),
(6, 1, 'Away Win', '1X2', 5.00),
(6, 1, 'Over 2.5 Goals', 'Goals O/U', 1.60),
(6, 1, 'Both Teams to Score - Yes', 'BTTS', 1.65);

-- ============================================================================
-- SAMPLE AI PREDICTIONS
-- ============================================================================

INSERT INTO ai_predictions (match_id, model_id, prediction_type_id, prediction_value, confidence, probability, reasoning) VALUES
(1, 1, 1, 'Home Win', 75, 0.75, 'Arsenal strong home form (5 wins in last 6). Chelsea struggling away with 3 losses in last 5 away games.'),
(1, 4, 6, 'Over 2.5', 70, 0.70, 'Both teams averaging 2.8 goals per game. Head-to-head shows 4 of last 5 meetings had 3+ goals.'),
(1, 6, 10, 'BTTS Yes', 78, 0.78, 'Arsenal scored in all home games. Chelsea scored in 8 of 10 away games.'),

(4, 1, 1, 'Home Win', 55, 0.55, 'Barcelona slight edge at Camp Nou. Recent form similar but home advantage crucial in El Clásico.'),
(4, 6, 6, 'Over 2.5', 82, 0.82, 'El Clásico averaging 3.5 goals. Both teams in attacking form with combined 15 goals in last 5 games.'),

(6, 1, 1, 'Home Win', 80, 0.80, 'Bayern dominant at home (90% win rate). Dortmund missing key defenders. Bayern 12-game unbeaten streak.'),
(6, 6, 10, 'BTTS Yes', 85, 0.85, 'Both teams high-scoring. Dortmund always competitive offensively despite defensive issues.');

-- ============================================================================
-- NOTIFICATIONS (for testing)
-- ============================================================================

-- Note: These will be empty initially as they're user-specific
-- They'll be populated as users interact with the system

-- ============================================================================
-- CHAT ROOMS
-- ============================================================================

INSERT INTO chat_rooms (id, name, room_type, match_id, league_id, participant_count) VALUES
(1, 'General Discussion', 'general', NULL, NULL, 0),
(2, 'Premier League Chat', 'league_specific', NULL, 1, 0),
(3, 'La Liga Chat', 'league_specific', NULL, 2, 0),
(4, 'Bundesliga Chat', 'league_specific', NULL, 3, 0),
(5, 'Arsenal vs Chelsea Match Thread', 'match_specific', 1, 1, 0),
(6, 'Barcelona vs Real Madrid Match Thread', 'match_specific', 4, 2, 0),
(7, 'Bayern vs Dortmund Match Thread', 'match_specific', 6, 3, 0);

-- ============================================================================
-- END OF SEED DATA
-- ============================================================================

-- Summary:
-- - 7 Leagues
-- - 8 Venues
-- - 20 Teams
-- - 15 Prediction Types
-- - 6 AI Models
-- - 8 Bookmakers
-- - 24 Achievement Definitions
-- - 6 Challenge Definitions
-- - 3 Tournaments
-- - 10 Sample Matches
-- - 20+ Sample Odds
-- - 7+ Sample AI Predictions
-- - 7 Chat Rooms
